name: CustomEnchants
version: 1.0.0
author: UselessMC
main: me.UselessMC.CustomEnchants.Main
api-version: 1.17
commands:
  telekinesisbook:
    usage: /<command>
  autosmeltbook:
    usage: /<command>