package me.UselessMC.luckyOres;

import java.util.ArrayList;

import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;
import org.bukkit.plugin.java.JavaPlugin;

import me.UselessMC.luckyOres.OreBreakEvent.OreBreakEvent;
import me.UselessMC.luckyOres.lapisBooks.lapisBooks;

public class Main extends JavaPlugin{
	public static ArrayList<ItemStack> coalitems = new ArrayList<ItemStack>();
	public static ArrayList<ItemStack> ironitems = new ArrayList<ItemStack>();
	public static ArrayList<ItemStack> golditems = new ArrayList<ItemStack>();
	public static ArrayList<ItemStack> diamonditems = new ArrayList<ItemStack>();
	public static ArrayList<ItemStack> redstoneitems = new ArrayList<ItemStack>();
	public static ArrayList<ItemStack> lapisitems = new ArrayList<ItemStack>();
	public static ArrayList<ItemStack> emeralditems = new ArrayList<ItemStack>();
	public static ArrayList<ItemStack> netheriteitems = new ArrayList<ItemStack>();
	@Override
	public void onEnable() {
		lapisBooks.init();
		getServer().getPluginManager().registerEvents(new OreBreakEvent(), this);
		coalitems.add(new ItemStack(Material.COAL_BLOCK, 2));
		coalitems.add(new ItemStack(Material.COAL_BLOCK, 2));
		coalitems.add(new ItemStack(Material.STONE_AXE, 1));
		coalitems.add(new ItemStack(Material.STONE_PICKAXE, 1));
		coalitems.add(new ItemStack(Material.STONE_SHOVEL, 1));
		coalitems.add(new ItemStack(Material.STONE_SWORD, 1));
		ironitems.add(new ItemStack(Material.IRON_INGOT, 5));
		ironitems.add(new ItemStack(Material.IRON_INGOT, 5));
		ironitems.add(new ItemStack(Material.IRON_INGOT, 5));
		ironitems.add(new ItemStack(Material.IRON_CHESTPLATE, 1));
		ironitems.add(new ItemStack(Material.IRON_LEGGINGS, 1));
		ironitems.add(new ItemStack(Material.IRON_BOOTS, 1));
		ironitems.add(new ItemStack(Material.IRON_HELMET, 1));
		ironitems.add(new ItemStack(Material.IRON_AXE, 1));
		ironitems.add(new ItemStack(Material.IRON_PICKAXE, 1));
		golditems.add(new ItemStack(Material.GOLD_INGOT, 4));
		golditems.add(new ItemStack(Material.GOLD_INGOT, 4));
		golditems.add(new ItemStack(Material.GOLD_INGOT, 4));
		golditems.add(new ItemStack(Material.GOLDEN_APPLE, 2));
		golditems.add(new ItemStack(Material.GLISTERING_MELON_SLICE, 4));
		golditems.add(new ItemStack(Material.GOLDEN_CARROT, 6));
		golditems.add(new ItemStack(Material.GOLD_INGOT, 4));
		golditems.add(new ItemStack(Material.GOLD_INGOT, 4));
		golditems.add(new ItemStack(Material.GOLD_INGOT, 4));
		golditems.add(new ItemStack(Material.GOLDEN_APPLE, 2));
		golditems.add(new ItemStack(Material.GLISTERING_MELON_SLICE, 4));
		golditems.add(new ItemStack(Material.GOLDEN_CARROT, 6));
		golditems.add(new ItemStack(Material.GOLDEN_APPLE, 2));
		golditems.add(new ItemStack(Material.GLISTERING_MELON_SLICE, 4));
		golditems.add(new ItemStack(Material.GOLDEN_CARROT, 6));
		golditems.add(new ItemStack(Material.ENCHANTED_GOLDEN_APPLE, 1));
		diamonditems.add(new ItemStack(Material.DIAMOND, 2));
		diamonditems.add(new ItemStack(Material.DIAMOND_CHESTPLATE, 1));
		diamonditems.add(new ItemStack(Material.DIAMOND_LEGGINGS, 1));
		diamonditems.add(new ItemStack(Material.DIAMOND_BOOTS, 1));
		diamonditems.add(new ItemStack(Material.DIAMOND_HELMET, 1));
		diamonditems.add(new ItemStack(Material.DIAMOND_SWORD, 1));
		diamonditems.add(new ItemStack(Material.DIAMOND_PICKAXE, 1));
		diamonditems.add(new ItemStack(Material.DIAMOND_AXE, 1));
		diamonditems.add(new ItemStack(Material.DIAMOND_HOE, 1));
		redstoneitems.add(new ItemStack(Material.REDSTONE, 12));
		redstoneitems.add(new ItemStack(Material.REDSTONE, 12));
		redstoneitems.add(new ItemStack(Material.REDSTONE_BLOCK, 2));
		redstoneitems.add(new ItemStack(Material.REDSTONE_BLOCK, 2));
		redstoneitems.add(new ItemStack(Material.REPEATER, 4));
		redstoneitems.add(new ItemStack(Material.COMPARATOR, 4));
		redstoneitems.add(new ItemStack(Material.PISTON, 6));
		redstoneitems.add(new ItemStack(Material.STICKY_PISTON, 6));
		redstoneitems.add(new ItemStack(Material.REDSTONE_TORCH, 12));
		redstoneitems.add(new ItemStack(Material.OBSERVER, 4));
		redstoneitems.add(new ItemStack(Material.TARGET, 3));
		redstoneitems.add(new ItemStack(Material.HOPPER, 4));
		lapisitems.add(new ItemStack(Material.LAPIS_LAZULI, 8));
		lapisitems.add(new ItemStack(Material.LAPIS_LAZULI, 8));
		lapisitems.add(new ItemStack(Material.LAPIS_LAZULI, 8));
		lapisitems.add(lapisBooks.opefficiency);
		lapisitems.add(lapisBooks.opfalling);
		lapisitems.add(lapisBooks.opflame);
		lapisitems.add(lapisBooks.opfortune);
		lapisitems.add(lapisBooks.opinfinity);
		lapisitems.add(lapisBooks.opknockback);
		lapisitems.add(lapisBooks.oplooting);
		lapisitems.add(lapisBooks.oppower);
		lapisitems.add(lapisBooks.opprotection);
		lapisitems.add(lapisBooks.oppunch);
		lapisitems.add(lapisBooks.opsharp);
		lapisitems.add(lapisBooks.opthorns);
		lapisitems.add(lapisBooks.opfire);
		emeralditems.add(new ItemStack(Material.EMERALD, 3));
		emeralditems.add(new ItemStack(Material.EXPERIENCE_BOTTLE, 64));
		emeralditems.add(new ItemStack(Material.BOOKSHELF, 3));
		emeralditems.add(new ItemStack(Material.ANVIL, 1));
		emeralditems.add(new ItemStack(Material.TOTEM_OF_UNDYING, 1));
		emeralditems.add(new ItemStack(Material.EXPERIENCE_BOTTLE, 64));
		emeralditems.add(new ItemStack(Material.BOOKSHELF, 3));
		emeralditems.add(new ItemStack(Material.ANVIL, 1));
		emeralditems.add(new ItemStack(Material.TOTEM_OF_UNDYING, 1));
		emeralditems.add(new ItemStack(Material.TOTEM_OF_UNDYING, 1));
		netheriteitems.add(new ItemStack(Material.NETHERITE_SCRAP, 2));
		netheriteitems.add(new ItemStack(Material.NETHERITE_INGOT, 1));
		netheriteitems.add(new ItemStack(Material.NETHERITE_HOE, 1));
		netheriteitems.add(new ItemStack(Material.NETHERITE_HOE, 1));
		netheriteitems.add(new ItemStack(Material.NETHERITE_SWORD, 1));
		netheriteitems.add(new ItemStack(Material.NETHERITE_AXE, 1));
		netheriteitems.add(new ItemStack(Material.NETHERITE_HELMET, 1));
		netheriteitems.add(new ItemStack(Material.NETHERITE_BOOTS, 1));
		netheriteitems.add(new ItemStack(Material.NETHERITE_SHOVEL, 1));
	}
}
